stages:
  - build
  - update-manifest
variables:
  APP_NAME: "final-exam-"
  DOCKER_IMAGE: $DOCKER_USER_NAME/${APP_NAME}${CI_PROJECT_NAME}:$CI_COMMIT_SHA

docker_build:
  image: docker:24.0.7
  stage: build
  before_script:
    - docker login -u $DOCKER_USER_NAME -p $DOCKER_PASSWORD
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

update-manifest:
    stage: update-manifest
    variables:
        APP_NAME: "final-exam-"
        DOCKER_IMAGE: $DOCKER_USER_NAME/${APP_NAME}${CI_PROJECT_NAME}:$CI_COMMIT_SHA
        MANIFEST_GIT_REPO: https://$USERNAME:$PAT_TOKEN@git.gebeya.training/Aron/final-exam-deployment-manifest.git
    before_script:
        - apk add git
        - git clone $MANIFEST_GIT_REPO
        - git config --global user.name "$GITLAB_USER_NAME"
        - git config --global user.email "$GITLAB_USER_EMAIL"
    script:
        - cd final-exam-deployment-manifest
        - git remote set-url origin --push $MANIFEST_GIT_REPO
        - |
            sed -i "s#image:.*#image: ${DOCKER_IMAGE}#g" ./frontend/frontend-deploy.yaml
        - git stage ./frontend/frontend-deploy.yaml
        - git commit -m "Update the frontend image tag [skip-ci]"
        - git push origin HEAD:$CI_COMMIT_REF_NAME

#change