name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag aron918/my-portifello-ci-cd-git-workflow:${{ github.sha }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker image to Docker Hub
        run: docker push aron918/my-portifello-ci-cd-git-workflow:${{ github.sha }}
 
  update-manifest:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout manifest repository
        uses: actions/checkout@v2
        with:
          repository: aron001/full-ci-cd-devops-portfolio-web-app-deployment-manifest.git
          ref: main

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Update manifest
        run: |
          sed -i "s#image:.*#image: aron918/my-portifello-ci-cd-git-workflow:${{ github.sha }}#g" ./frontend-deploy.yaml
          git add ./frontend-deploy.yaml
          git commit -m "Update the frontend image tag [skip ci]"
          git remote add origin_with_token https://aron001:${{ secrets.PAT }}@github.com/aron001/full-ci-cd-devops-portfolio-web-app-deployment-manifest.git
          git push origin_with_token HEAD:main
# comment added
